# Disable the "core" platformsh plugins
disablePlugins:
  - lando-platformsh
  - lando-upsun

# Make sure we are dogfooding this plugin for testing purposes
plugins:
  "@lando/upsun": /home/runner/work/upsun/upsun

# Disable metrics reporting
stats:
  - report: false
    url: https://metrics.lando.dev


