name: "@lando/upsun"

# Lando 3 autoscans builders/, inits/, scripts/ and app.js for legacy plugins
legacy: true

docs:
  tag: upsun
  guides:
    title: Upsun
    collapsable: true
    children:
      "docs/guides/adding-more-tooling": upsun/adding-more-tooling
      "docs/guides/external-access": upsun/external-access
      "docs/guides/manually-importing-databases": upsun/manually-importing-databases
      "docs/guides/xdebug": upsun/xdebug
  config:
    recipes:
      "upsun": ./docs/config.md
