'use strict';

const {shellArgument} = require('../shell');

const UNSUPPORTED_EXTENSIONS = Object.freeze(['blackfire', 'newrelic', 'sourceguardian', 'ioncube']);
const DEPENDENCY_GROUPS = Object.freeze(['nodejs', 'php', 'python', 'python2', 'python3', 'ruby']);

const iniValue = value => {
  let rendered = value;
  if (typeof value === 'boolean') rendered = value ? 'On' : 'Off';
  if (Array.isArray(value)) rendered = value.join(',');
  rendered = String(rendered);
  return /[^A-Za-z0-9_./:@-]/.test(rendered) ? `"${rendered.replace(/"/g, '\\"')}"` : rendered;
};

const flattenIni = (variables, prefix = '') => Object.entries(variables || {}).flatMap(([key, value]) => {
  const name = prefix ? `${prefix}.${key}` : key;
  if (value && typeof value === 'object' && !Array.isArray(value)) return flattenIni(value, name);
  return [[name, value]];
});

/**
 * Renders normalized variables.php values as a PHP ini fragment.
 *
 * @param {object} variables PHP variables.
 * @returns {string}
 */
const renderPhpIni = variables => [
  '; Generated by @lando/upsun from variables.php',
  ...flattenIni(variables).map(([key, value]) => `${key} = ${iniValue(value)}`),
  '',
].join('\n');

/**
 * Builds the local PHP extension setup step and identifies unsupported extensions.
 *
 * @param {object} runtime Normalized runtime configuration.
 * @returns {{step: string|null, unsupported: string[]}}
 */
const getExtensionStep = (runtime = {}) => {
  const enabled = [...new Set(runtime.extensions || [])];
  const disabled = [...new Set(runtime.disabled_extensions || [])];
  for (const extension of [...enabled, ...disabled]) {
    if (!/^[a-z0-9_]+$/i.test(extension)) throw new Error(`Invalid PHP extension: ${extension}`);
  }
  const unsupported = [...new Set([...enabled, ...disabled].filter(extension =>
    UNSUPPORTED_EXTENSIONS.includes(extension)))];
  const installableEnabled = enabled.filter(extension => !UNSUPPORTED_EXTENSIONS.includes(extension));
  const installableDisabled = disabled.filter(extension => !UNSUPPORTED_EXTENSIONS.includes(extension));
  const args = [];
  if (installableEnabled.length) args.push(`--enable ${installableEnabled.join(',')}`);
  if (installableDisabled.length) args.push(`--disable ${installableDisabled.join(',')}`);
  return {
    step: args.length ? `/helpers/upsun-php-extensions.sh ${args.join(' ')}` : null,
    unsupported,
  };
};

const dependencyStep = (group, name, version) => {
  const pinned = ![true, '*', 'latest'].includes(version);
  if (group === 'nodejs') return `npm install -g ${shellArgument(`${name}${pinned ? `@${version}` : ''}`)}`;
  if (group === 'php') return `composer global require ${shellArgument(`${name}${pinned ? `:${version}` : ''}`)}`;
  if (group.startsWith('python')) {
    return `pip install --user ${shellArgument(`${name}${pinned ? `==${version}` : ''}`)}`;
  }
  return `gem install ${shellArgument(name)}${pinned ? ` -v ${shellArgument(version)}` : ''}`;
};

/**
 * Renders application dependency installation steps in runtime group order.
 *
 * @param {object} dependencies Normalized application dependencies.
 * @returns {string[]}
 */
const getDependencySteps = (dependencies = {}) => DEPENDENCY_GROUPS.flatMap(group =>
  Object.entries(dependencies[group] || {})
      .sort(([left], [right]) => left.localeCompare(right))
      .filter(([name, version]) => name !== 'composer/composer' && version !== false && version !== null)
      .map(([name, version]) => dependencyStep(group, name, version)));

exports.getDependencySteps = getDependencySteps;
exports.getExtensionStep = getExtensionStep;
exports.renderPhpIni = renderPhpIni;
